server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userauth
    username: root
    password: password@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name : auth-service
eureka:
  client:
    serviceurl:
      defaultzone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistery: true
    registerWithEureka: true